[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
meteora_node = "9cTPBKLTSsrDNWNHFzkjctRQKPccE5MwCd51C9DTffF9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raunitjaiswal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
